name: kv-expiry-check
############################################################################################################################################
# 
# This pipeline checks all secrets on a keyvault (or vaults), and raises an alert if it will be expired in X amount of days
# The vaults to be checked and the check period are specified  in /templates/kv_secrets_expiry/list_expired_secrets.ps1
#
############################################################################################################################################
trigger: none
variables:
  azureServiceConnection: 'sp-lpdap-meta'

# The initialisation should run on a general agent
pool:
  name: LPDAP-Pool-general
stages:
  - stage: Check
    displayName: Checks
    jobs:
    - job: Deploy
      displayName: "Check KV expiry"
      steps:
    
      - task: AzurePowerShell@5
        displayName: 'Check powershell'
        inputs:
          azureSubscription: '${{variables.azureServiceConnection}}'
          ScriptPath: "$(Build.SourcesDirectory)/scripts/list_expired_secrets.ps1"
          azurePowerShellVersion: LatestVersion