trigger:  
pr: none
 
schedules:  
- cron: '0 0 1 */3 *'  # Runs at midnight on the 1st day of every 3rd month  
  branches:  
    include:  
      - main  
  
pool:
  name: LPDAP-Pool-general






steps:  
- bash: |  
    az storage account keys renew --account-name <storage account name> --resource-group <resource group name> --key primary  
  displayName: 'Rotate Storage Account Keys'  
  env:  
    AZURE_SERVICE_CONNECTION: ''  