env_variables:
  TFSTATE_RESOURCE_GROUP_NAME: rg-lpdapv001-meta
  TFSTATE_STORAGE_ACCOUNT_NAME: stlpdapv001metatfstate
versions:
  customer_workflow:
    artifact: v1.44.12
    environment_version: '01'
  individual:
    artifact: v1.15.18
    environment_version: '01'
  infra_modules:
    artifact: v15.4.0
  pensions:
    artifact: v1.21.8
    environment_version: '01'
