parameters:
  - name: domain
    type: string

  - name: post_deploy_job
    type: string
    default: " "

stages:
  - template: templates/stage.deploy.yml@cicd
    parameters:
      environment: dev
      data_domain: ${{ parameters.domain }}
      post_deploy_job: ${{ parameters.post_deploy_job }}

  - stage: "Deploy_IAM_to_dev"
    displayName: Deploy IAM permissions for Databricks to dev
    dependsOn: ["deploy_${{ parameters.domain }}_to_dev"]
    jobs:
    - template: cicd/job.iam-databricks-jobs.yml@iam
      parameters:
        azureserviceconnection: "lpdap-iam-dev"
        env: dev
        domain: ${{ parameters.domain }}

  - template: templates/stage.deploy.yml@cicd
    parameters:
      environment: tst
      data_domain: ${{ parameters.domain }}
      post_deploy_job: ${{ parameters.post_deploy_job }}

  - stage: "Deploy_IAM_to_tst"
    displayName: Deploy IAM permissions for Databricks to tst
    dependsOn: ["deploy_${{ parameters.domain }}_to_tst"]
    jobs:
    - template: cicd/job.iam-databricks-jobs.yml@iam
      parameters:
        azureserviceconnection: "lpdap-iam-tst"
        env: tst
        domain: ${{ parameters.domain }}
